### PR TITLE
CMake: Changes to files compiled when INCLFLO_DIM=2

### PR DESCRIPTION
**Pull request by etpalmer63**
This PR adds a condition to check the value of `INCFLO_DIM`. If it is not 3, the following files are no longer compiled:

```
      eb_spherecube.cpp
      eb_tuscan.cpp
      eb_twocylinders.cpp
```

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
Maybe the PR should be based on the current development branch, not a branch that's work-in-progress.

**Comment by etpalmer63** [comment]
I did a rebase to try to fix the issue. Is this the right way to fix it? Or should I close and do a new PR?

**Comment by WeiqunZhang** [comment]
Looks good now.  But it seems that we could do it in a different style to reduce duplicated lines.  Include common files first and then conditionally include 3d only files.

**Comment by etpalmer63** [comment]
:+1: Good suggestion, I will fix it. Thanks!

**Comment by etpalmer63** [comment]
It just passed compile for 2D and 3D. I will test execution tomorrow, then mark ready if it passes.

**Comment by etpalmer63** [comment]
Tested without MPI and it passed.

**Pull request merged**
